package test.com.percussion.pso;

import com.percussion.pso.migration.site.SiteTools;
import junit.framework.TestCase;

/**
 * The class <code>SiteToolsTests</code> contains tests for the class {@link
 * <code>SiteTools</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 1/25/11 7:35 AM
 *
 * @author natechadwick
 *
 * @version $Revision$
 */
public class SiteToolsTests extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public SiteToolsTests(String name) {
		super(name);
	}

	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	protected void setUp() throws Exception {
		super.setUp();
		// Add additional set up code here
	}

	/**
	 * Perform post-test clean up
	 *
	 * @throws Exception
	 *
	 * @see TestCase#tearDown()
	 */
	protected void tearDown() throws Exception {
		super.tearDown();
		// Add additional tear down code here
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = true
 * createTearDown = true
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = test.com.percussion.pso
 * package.sourceFolder = PSOServerCleanupTool/src
 * superclassType = junit.framework.TestCase
 * testCase = SiteToolsTests
 * testClassType = com.percussion.pso.migration.site.SiteTools
 */